### ISSUE TITLE
Spore Blossom

### ISSUE THREAD

**Issue by agentmelanylove** [Michaelcraun/MCCrafting#16]
### Context
**What item are you trying to craft?**
Spore Blossom

**Is this item something you currenlty cannot craft?** (<--Spelling error)
- [X] Yes
- [ ] No

**What items should be used to craft this item?**
Suggesting Lilac surrounded by moss block?

**Are there any other items that could be used to craft this item?**
Drip leaf, bonemeal, peonies, seeds?

**Has the recipe been requested before?** 
*(If this feature has been requested before, please provide a link to the issue.)*
- [ ] Yes
- [X] No

**Comment by agentmelanylove** [comment]
Prefer to keep at 2 ingredients for simplicity.

**Comment by Michaelcraun** [comment]
Look at you go. ;)
